#define PARALLEL_SELECTION_LEN              188
#define PARALLELSELECTION_POS               0
#define PARALLELSELECTION_HALF_POS          22
#define PARALLELSELECTION_HALF_IMPROVED_POS 58
#define PARALLELSELECTION_BYTE_IMPROVED_POS 101
#define PARALLELSELECTION_BYTE_POS          157
